language: node_js
node_js: node
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
addons:
  chrome: stable
env:
  global:
  - secure: o3DHqf6tyeD6u4wNtep9+xTitJTGWpQOz/sOQ1Irl/4MCr5VlPdRa40XOHNFovWGlgHranAL6o+Y916ysyIl75Bzy7iGTIfO9pQBvp6aSgdx8lq8csK2s+jQ5M5iSJP350lr30M2TRAnSKk3TRvorwx3yj7ovqjnrlex+xeTQWwedrSg2gXsZ/Tmne5ZzZiRE2MIvtr4bdQH692VGCF5baMMs1t85wDJyufen1/wGw/x5KQ6urKqZdYTN0OJ+bdHwDh3QgexPSfXrecbcn5eMo6N14AtLSKzyeNjQ2bf8PnbxDPNvizgU0LV/uIoU4ZvtYulY+K4w9gheKg4P0Bat+/tQX0JfOomXzoafyN6GVTaYk7I9hinwJMLbaNNdKHOn1z8OfoC9AOszvbaxZ+/99M2oWmKeH/xoplZ689lt2zOjTfZjJm2E3rb0BDzgaDwu2Qmkf8wJG3Jh2jFdrYISP7sUFnzH2ONN19T6JDGo1mg0hNqfTTM4wLQZao8GOXXBUTcvOZv/r/hdC4u5mc8kBtzAk0o06Kyjt6KqZMb3nvQmv3Ck2+V8InF37MCIXuAlqXdb2HJUqTd5jWv9QrFYMsxy/Glej1xaT4MxILjePKYL4Mlpo9wRLgDNWgZRx5LR4v/FlKjnP72lnC6Hazd0XSKIDbWCfoqJlPsX6kWqk8=
  - secure: lgMAxhKEyI58e/pi/cDqZuZJRc1l/JFZ7uyhExzpgAbKs4mdkoSn/mm+GixhSJ9R5qQt6jQ+y6Pwx+0qBBLdhd5AXNcQVbYuZixRKYvznD8n3qbUUImDzn5fIlDoAbn5HlcI7LEoCah8JXeA0PntYXHH0uXfKjm4VBvmmQJGdZzmXDJkFX/aDTcmDl+23ZzmJtplDDLyMuO7/JmUbqm+YP5b1LJ5aqGpdtF2RrBIUIT0/N45K4w5i1H61Rw/DNZWiB8KOkROZqBAO82PU2FF1BMsPhafsYThnmVhFI2Gt7kZVWkKvtP9yfYWibDyaX/DDWH28jROXbypM9sK4S13YVWL2W08ehTfmTzkXo24mBOC6C2+wwfxR6S+t4XHtglJwq7cREH0saw2X6II/5jOaTk6D+zx4g0ZxtSmcf3NJYDYsqipkWjGhbpF4vHDRSaM3az0LcbZbdeZF9aJGK5bt+TsipPojjky7TswBtQtac7cQOcWF6i0KCMP6Wy51zr7BlSCi02Rv1Bv8uJNBkctQUrDgfttyIZvDdxi21CtU13SCAe16rO6WFfdyISkCXNJ4sK8I8qxtfeZIq+klGxb3U23L9OZqrPbBuzw1rLqwZhoZ79JQBB/wLIxNqlojs0iHyWwsbGir3DOCVarFifNPVxUs53RXGhSbGJ65I+NrNQ=
