language: node_js
node_js: node
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
addons:
  chrome: stable
env:
  global:
  # SAUCE_USERNAME
  - secure: RN0GD02n5oD3o1uI6z9GnnGqmx5zDvpyhbNDLxlytkMOlj4utxo0ehMKF+mjetfipazKEqft0l9Yof+hWkfu0m71VTYiHz5ESwLAXWJ554QGCOrDZkf7s49iNRsBgq8pEjGoP/MbqIoljghxDP75gsNkQBKhcQvTrKZsDFPrnuEs04UHG2MfOlSw2cxJOSrTk3OHBeaRbtCkKIBFE4lnGVyQXvxO++00aIl7Bxll1k1P85O+WSs7s9/PGS+tj3nOOo5PCHEts4NurRYGtnanZEdBQbpVaORh3PrLTzV77z9rwPVtyQEHs5CdAIMeZEf1eVfnWEpNQSXGCWHdi8tMeCYKfOwiegNEXZNWwQ70TGTBm5TbHQzZ4bOWDItFfQ3Anvnj6fOd8PdSea94skeNmsJCJUzQy1lqKHsjfeUwIkgXVkm4Y/8N+wtEErSOp7xPbIWF2E6nsheaVLZchODoMulbUHYBmqO4lIYvA8IMdUABrrNHM5u7zEiaxkbtPK1f00skmH3BpP3MOal8405dAhaCHNcAQ7U5j6xUdeBNatRzkZcGISuwH6Z4ryEWWX7jzYpC07szcZSxcFH0B4c6FwrErw6NPiGtmYtmrHVh/YxCJcBXnJQLaAgWKMxxKq42cCchy5zTPUkSr5w/uPRMFw3Qln7xfev6oTE5dK4jYuQ=
  # SAUCE_ACCESS_KEY
  - secure: CBUdUuk5euAJGkLLp+8z2rLpiNut0EcB1snySiAt4hx38xBCs75/zLZzz09v9HvSHsBdolvhEObQLwqKJbG3v7pl8pds5QxkWiIjyd2Efg98omkanYQmBwofyRjQ1xSkl1OY9fuejQYV/nHQwSRr1SeZ3FHPRthMhpUSJvBeilJvQuL7iL8JqDVYpEa/N52DJ9K1BYWgygxgqKjIj3MCGLcRY1da3oxFfhkOTFrHU1O/pJvGKKolNa9G0c0N7BkP1EwmnUs4De5nQNOaPouyWcBmvlHRbspTNe31ygKAxPAttEIvqXIeU/IWmbiLPwBYQ+wh5Z5/HzfEDpSx8g+DruXpg7a1JjlCyYQYXCzTTG/NRaGIsw9V/Q9Proz/y5zxpZZi/iLe1ObJOy9LVXOpOyYVeddG0vP/L5mFMZfwFKB8D3fA2ZYN+H0hu6sMZitG6X0ttw5qf97D5sUxZkvuP4m6m/nnmpb8zJGXV6muHxMH6b+mAy/aIMxg2+ZuZ77ElEvPVJhByxzX7TLzm4a5NG7iU10ZNwF6O8iYFtnbvyHa0bKelkayQ3x2i3sMLuiwY8ZOZvmfkDbprbZPhaW821+1DTlUjxDiJ471UAN1EBPKnZjEYnNkQyzPmf38vciI/2X57B5bEZOdmGrWWcUWwa1VtLQrCMj2BePIrtbg0ZM=
